### PR TITLE
German Localization

### PR DESCRIPTION
**Pull request by Kthargas**
I've worked on the German translation, but it may not be perfect yet.

### CODE REVIEW

**Comment by XMuli** [comment]
My friend, thank you very much. ❤
Your translation has been great and I will integrate it into the next version!

and have a good weekend.

**Comment by XMuli** [comment]
Translation language should be written between `<translation>` and `</translation>`.
Example: <source>Licenses</source>.


https://github.com/XMuli/SunnyPages/blob/45987f336a0c1527aa9efb273428e17d5f276ab8/translations/pt_br.ts#L7-L8

https://github.com/XMuli/SunnyPages/blob/45987f336a0c1527aa9efb273428e17d5f276ab8/translations/zh_cn.ts#L7-L8

https://github.com/XMuli/SunnyPages/blob/45987f336a0c1527aa9efb273428e17d5f276ab8/translations/zh_tw.ts#L7-L8

You can refer to the Chinese or Portuguese language [sample zh_cn.ts](https://github.com/XMuli/SunnyPages/blob/45987f336a0c1527aa9efb273428e17d5f276ab8/translations/zh_cn.ts)


In addition to merging issues (or using github / git / any other) have any questions, you can leave a message, I will help you to move forward to complete it!

**Comment by XMuli** [comment]
I have updated the contents of `de.ts`, here is the program with German integration, the preview program is as follows

**File:** [Sunny_protable_1.6.3_x64.zip](https://github.com/XMuli/SunnyPages/files/15434403/Sunny_protable_1.6.3_x64.zip)

image

**Comment by Kthargas** [comment]
Oh, then I made a mistake here. Now I understand the syntax of this file, sorry. 
I saw that the translations for the Tokens tab are missing and that there is an incorrect translation for the orientation under Personalization. 
Should I revise the file with the correct syntax and missing translations?

PS: I love this project. It's much better than any other screenshot software I've used so far, great work!
I am glad to help.

**Comment by XMuli** [comment]
Thanks for the favorites and the language translations
I've updated the README and [de.ts](https://github.com/XMuli/SunnyPages/blob/master/translations/de.ts), so you can change them directly here.

**Comment by XMuli** [comment]
Use [Qt Linguist](https://github.com/lelegard/qtlinguist-installers/releases) to open the .ts, edit it, save it and you're done, it's a better experience than notepad!

**Pull request merged**
