### PR TITLE
Update Sunny_pt_BR.ts

### PR DESCRIPTION
**Pull request by thiagodalsoto**
I don't know how to use git here... I first sent it to your email, but I believe I managed to do it

for "tech.xmuli.sunny.desktop" shortcuts.

Comment[pt_BR]=Sunny é uma ferramenta de software de captura de tela simples e bonita para Windows, MacOS e Linux
GenericName[pt_BR]=Sunny Captura de Tela
Name[pt_BR]=Sunny

### CODE REVIEW

**Comment by XMuli** [comment]
Surprise buzz(*°▽°*)╯

Thanks for your contribution, I'll make it work in the next version and let you know;

Sorry for forgetting the difficulty of using git, but this PR is great. If you have any questions about how to use it, please contact me at ISSUSE or gmail.
I'll move the translation to another convenient platform later, do you have any suggestions for this?

**Comment by thiagodalsoto** [comment]
Your method is great, git must certainly be one of the best places for this... I've never spent even 10 minutes on the tool and I don't know how to use it, but I believe I managed to post the work. Congratulations on the capture software, it works beautifully on my Ubuntu 24.04 :)

A tip, maybe it's overzealous, but it's worth polishing the edge of the icon that is in the top bar of the gnome

**Comment by XMuli** [comment]
Yes, Portuguese-Spanish is already working fine.

The logo is generated by chatgpt, I'll tweak it at a later stage when there's a better design, and I'll keep an eye on how it looks on gnome!

**Comment by XMuli** [comment]
I would also like to ask which name and link you would like to show on the acknowledgement page of this software? By default, the following will be displayed
Name: Thiago
URL: https://github.com/thiagodalsoto

**Comment by thiagodalsoto** [comment]
> I would also like to ask which name and link you would like to show on the acknowledgement page of this software? By default, the following will be displayed
> 
> ```
> Name: Thiago
> URL: https://github.com/thiagodalsoto
> ```

No need to worry about that, the idea was just to collaborate, making the experience in my local language, so for all users in Brazilian Portuguese

But if you're going to use something, you can use my name without any problems;
Name: Thiago Dalsoto
URL: https://github.com/thiagodalsoto

**Comment by XMuli** [comment]
Updated, see Portugal-Brazil translation results in v1.6.2

**Pull request merged**
